# Establecer la fuente de texto a JetBrains Mono
#font_family JetBrainsMono Nerd Font Mono

# Establecer el tamaño de la fuente (ajústalo a tu preferencia)
#font_size 15.0
#enable_italic yes

#######################################
font_family JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13
background_opacity 0.85
background_blur 90

# Special
background #000000 
#14151e 
#1A333A 
foreground #009999 
#00D1D1 
#98b0d3 

# Black
color0  #151720
color8  #616161
#4f5572 

# Red
color1 #E51A1A 
color9 #e26c7c

# Green
color2 #1AE51A
color10 #95d3af

# Yellow
color3 #E5BD1A  
#ecd3a0
color11 #f1d8a5

# Blue
color4 #008DFF
#86aaec
color12 #8baff1

# Magenta
color5 #E800FF  
#c296eb
color13 #c79bf0

# Cyan
color6 #00FFEA  
#93cee9
color14 #98d3ee

# White
color7  #cbced3
color15 #d0d3d8

# Cursor
cursor #cbced3
cursor_text_color #a5b6cf

# Configurar el cursor
cursor_shape beam
cursor_blinking yes

# Selection highlight
selection_foreground #a5b6cf
selection_background #1c1e27


# The color for highlighting URLs on mouse-over
# url_color #9ece6a
url color #5de4c7

# Window borders
active_border_color #3d59a1
inactive_border_color #101014
bell_border_color #fffac2

# Activar aceleración de hardware
use_system_font yes


# Tab bar

tab_bar_style fade
tab_fade 1
active_tab_foreground   #3d59a1
active_tab_background   #16161e
active_tab_font_style   bold
inactive_tab_foreground #787c99
inactive_tab_background #16161e
inactive_tab_font_style bold
tab_bar_background #101014

